# This file was generated by GoReleaser. DO NOT EDIT.
cask "lancert" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "291d09ea6d805aa08afc7511323cecd93e4d67af51f2328ab5fecdf151fd2dfb"
      url "https://github.com/lucor/lancert-cli/releases/download/v#{version}/lancert_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b197d3f98ea0b66c9f0f5a2c8ce0b28f336109ef40c0250b908191d95561aff"
      url "https://github.com/lucor/lancert-cli/releases/download/v#{version}/lancert_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c9f0d0fadfa5dcde371214b02136861888f804e0fe9ba77f8148fd01ccda943"
      url "https://github.com/lucor/lancert-cli/releases/download/v#{version}/lancert_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "05c0b172c40579ed6bab2e22fb5b8b75dc0677f08678076d4bf4c2623b683df3"
      url "https://github.com/lucor/lancert-cli/releases/download/v#{version}/lancert_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lancert"
  desc "Local HTTPS certificates for private IP addresses"
  homepage "https://lancert.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lancert"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lancert"]
    end
  end

  # No zap stanza required

end
