# This file was generated by GoReleaser. DO NOT EDIT.
cask "lancert" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "72f4394cfc8c1a10a7e8f2c9625dbe207014b5a009c970b16da1aa2702e6918b"
      url "https://github.com/lucor/lancert-cli/releases/download/v#{version}/lancert_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "db32cf8d4119c40c834379907ee3a9a65c58e6dc15433f5a7dc531fcd8e60b9a"
      url "https://github.com/lucor/lancert-cli/releases/download/v#{version}/lancert_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9799a201f71dc2c0f3d241c507e49a9bc2e2106973dce1d976474470f8f0b70c"
      url "https://github.com/lucor/lancert-cli/releases/download/v#{version}/lancert_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "de859eb75e404527c1b2e33436645f98a6573b42535a43d769ea03c4d617163d"
      url "https://github.com/lucor/lancert-cli/releases/download/v#{version}/lancert_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lancert"
  desc "Local HTTPS certificates for private IP addresses"
  homepage "https://lancert.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lancert"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lancert"]
    end
  end

  # No zap stanza required

end
