# This file was generated by GoReleaser. DO NOT EDIT.
cask "lancert" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c0749c093c4aef58f25a42f6ba5beea22094a62bf099349b54b5acdc81c7c2ef"
      url "https://github.com/lucor/lancert-cli/releases/download/v#{version}/lancert_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e44efc227736eb11104a7103ecc42e2d5f3151030d70709512db5132355c270d"
      url "https://github.com/lucor/lancert-cli/releases/download/v#{version}/lancert_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b1f65f57c225ce0e30d7e0bc8b984163ab6426ab1f53b64ce6e89fcdaadd947"
      url "https://github.com/lucor/lancert-cli/releases/download/v#{version}/lancert_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad18b63bfd84637e01b066aa31c32a9bab5963f1937441f3456970b73d02204a"
      url "https://github.com/lucor/lancert-cli/releases/download/v#{version}/lancert_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lancert"
  desc "Local HTTPS certificates for private IP addresses"
  homepage "https://lancert.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lancert"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lancert"]
    end
  end

  # No zap stanza required

end
